import { defineConfig } from 'tsup'
import { readTsupExternalSync } from './external-sync.mjs'
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'

/**
 * Derive tsup entry points from package.json.
 * Reads two sources of published dist artifacts:
 *   1. `exports` — public module surface ("./dist/foo.js" → "src/foo.ts")
 *   2. `kb.manifest` — plugin/adapter manifest loaded at runtime by the
 *      kb-labs platform; it's referenced as a dist path but not exported,
 *      so it would otherwise be silently omitted from the build.
 * Falls back to ['src/index.ts'] if nothing resolves.
 */
function resolveEntryFromExports() {
  try {
    const pkgPath = join(process.cwd(), 'package.json')
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
    const srcFiles = new Set()

    const distPaths = []
    for (const condition of Object.values(pkg.exports ?? {})) {
      const importPath = typeof condition === 'string' ? condition
        : (condition.import ?? condition.default ?? null)
      if (importPath && typeof importPath === 'string') distPaths.push(importPath)
    }
    if (typeof pkg.kb?.manifest === 'string') distPaths.push(pkg.kb.manifest)

    for (const p of distPaths) {
      const base = p.replace(/^\.\/dist\//, '').replace(/\.js$/, '')
      const candidates = [`src/${base}.ts`, `${base}.ts`]
      for (const c of candidates) {
        if (existsSync(join(process.cwd(), c))) { srcFiles.add(c); break }
      }
    }

    return srcFiles.size > 0 ? Array.from(srcFiles) : ['src/index.ts']
  } catch {
    return ['src/index.ts']
  }
}

/**
 * Resolve the absolute path of the built manifest module (e.g. dist/manifest.js)
 * from `pkg.kb.manifest`, or null when the package ships no service/plugin
 * manifest. Used to materialize a sibling dist/manifest.json after build.
 */
function resolveManifestDistPath() {
  try {
    const pkg = JSON.parse(readFileSync(join(process.cwd(), 'package.json'), 'utf8'))
    if (typeof pkg.kb?.manifest === 'string') {
      return join(process.cwd(), pkg.kb.manifest.replace(/^\.\//, ''))
    }
  } catch {
    // No package.json / no manifest — nothing to emit.
  }
  return null
}

/**
 * tsup `onSuccess`: emit dist/manifest.json next to the built dist/manifest.js.
 *
 * The kb-labs runtime loads manifests by importing the JS module, but Go-based
 * installers (kb-create) read the manifest as JSON — `kb-create swap` looks for
 * `dist/manifest.json` and silently skips service registration when it is
 * absent. Materializing the JSON from the just-built module keeps a single
 * source of truth (src/manifest.ts) while satisfying both consumers.
 */
async function emitManifestJson() {
  const manifestDist = resolveManifestDistPath()
  if (!manifestDist || !existsSync(manifestDist)) return
  try {
    // Cache-bust so watch-mode rebuilds re-read the fresh module.
    const url = pathToFileURL(manifestDist).href + `?t=${Date.now()}`
    const mod = await import(url)
    const manifest = mod.default ?? mod.manifest
    if (!manifest || typeof manifest !== 'object') return
    // Scope to SERVICE manifests — the only ones kb-create reads as JSON.
    // Plugin/adapter manifests are loaded as JS by the runtime and don't need
    // a sibling .json (and may carry side-effectful imports we shouldn't run).
    if (typeof manifest.schema !== 'string' || !manifest.schema.startsWith('kb.service/')) return
    const jsonPath = manifestDist.replace(/\.js$/, '.json')
    writeFileSync(jsonPath, JSON.stringify(manifest, null, 2) + '\n')
  } catch {
    // Never fail the build over manifest emission — absence just means the
    // service won't auto-register, which is the pre-existing behaviour.
  }
}

function resolveExternalDependencies() {
  try {
    const pkgPath = join(process.cwd(), 'package.json')
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
    const deps = Object.keys(pkg.dependencies ?? {})
    const peerDeps = Object.keys(pkg.peerDependencies ?? {})
    return Array.from(new Set([...deps, ...peerDeps]))
  } catch {
    return []
  }
}

function getExternal() {
  // Try to use generated tsup.external.json if available
  // This file should be generated by kb-devkit-tsup-external and contains:
  // - All @kb-labs/* workspace packages (found via pnpm-workspace.yaml)
  // - All dependencies and peerDependencies from package.json
  try {
    const generated = readTsupExternalSync()
    if (generated.length > 0) {
      return generated
    }
  } catch {
    // If reading fails, fallback to package.json
  }
  // Fallback to reading package.json directly
  return resolveExternalDependencies()
}

// Pre-compute external list and entry once at module load time
const externalList = getExternal()
const entryFromExports = resolveEntryFromExports()

export default defineConfig({
  entry: entryFromExports,
  format: ['esm'],
  target: 'es2022',
  sourcemap: true,
  clean: true,
  dts: true,
  treeshake: true,
  minify: false,
  outDir: 'dist',
  splitting: false,
  skipNodeModulesBundle: true,
  shims: false,
  // Emit dist/manifest.json from the built manifest module so Go installers
  // (kb-create) can register the service. No-op for packages without a manifest.
  onSuccess: emitManifestJson,
  ignoreWatch: [
    '**/node_modules/**',
    '**/dist/**',
    '**/.git/**',
  ],
  // Mark all node_modules packages as external (including transitive deps)
  // Use noExternal: [] to prevent bundling any node_modules packages
  // This is more reliable than regex for ensuring transitive deps stay external
  noExternal: [],
  external: [
    /^[^./]|^\.[^./]|^\.\.[^/]/, // All node_modules packages (not relative paths)
    // All workspace packages from tsup.external.json (generated by kb-devkit-tsup-external)
    // This includes all @kb-labs/* packages found in pnpm-workspace.yaml
    // plus dependencies/peerDependencies from package.json
    ...externalList, // Explicitly listed packages (workspace + local deps)
    // Force all @kb-labs packages to be external
    // This catches packages linked via "link:" protocol that might not be in the workspace scan
    /^@kb-labs\//,
  ],
})
