packages:
  - core/*
  - sdk/*
  - cli/*
  - shared/*
  - plugins/*/*
  - '!plugins/fixtures/*'
  - adapters/*
  - infra/devkit
  - studio/*
  - sites/*
  - sites/*/apps/*
  - sites/*/packages/*
  - templates/*
  - templates/*/packages/*
  - .kb/plugins/*/packages/*
