packages:
  - e2e/shared
  - e2e/services
  - e2e/platform
  - e2e/gateway
  - e2e/marketplace
  - e2e/marketplace-registry
  - e2e/workflows
  - e2e/studio
  - e2e/plugins
  - e2e/rest-api
  - core/*
  - sdk/*
  - cli/*
  - shared/*
  - plugins/*/*
  - '!plugins/fixtures/*'
  - adapters/*
  - infra/devkit
  - studio/*
  - sites/*
  - sites/*/apps/*
  - sites/*/packages/*
  - templates/*
  - templates/*/packages/*
  - .kb/plugins/*/packages/*
