package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/kb-labs/create/internal/claude"
	"github.com/kb-labs/create/internal/config"
	"github.com/kb-labs/create/internal/platform"
	"github.com/kb-labs/create/internal/userstate"
)

var flagUninstallYes bool

var uninstallCmd = &cobra.Command{
	Use:   "uninstall",
	Short: "Remove an installed platform",
	Long: `Removes the platform directory, project .kb config, and CLI symlinks.

This is a destructive operation — all installed packages, configs,
and cached data in the platform directory will be deleted. User-authored
project files and .kb artifacts are preserved.`,
	RunE: runUninstall,
}

func init() {
	rootCmd.AddCommand(uninstallCmd)
	uninstallCmd.Flags().BoolVarP(&flagUninstallYes, "yes", "y", false, "skip confirmation prompt")
}

func runUninstall(cmd *cobra.Command, args []string) error {
	out := newOutput()

	platformDir, err := resolvePlatformDirForUninstall(cmd)
	if err != nil {
		return err
	}

	cfg, err := config.Read(platformDir)
	if err != nil {
		return err
	}

	out.Section("Uninstall KB Labs")
	out.KeyValue("Platform", platformDir)
	out.KeyValue("Project", cfg.CWD)
	fmt.Println()

	out.Warn("This will permanently delete:")
	fmt.Printf("  • %s (all packages, configs, logs)\n", platformDir)
	fmt.Printf("  • generated platform pointer in %s/.kb/ (if present)\n", cfg.CWD)
	fmt.Printf("  • ~/.local/bin/kb (CLI symlink)\n")
	fmt.Printf("  • ~/.local/bin/kb-dev (service manager symlink)\n")
	fmt.Println()

	if !flagUninstallYes && !confirmDestructive("Are you sure? [y/N] ") {
		out.Info("Cancelled.")
		return nil
	}

	// Remove Claude Code assets first (skills + managed CLAUDE.md section).
	// Done before the platform dir is removed so that the resolver can still
	// find the devkit manifest if needed for diagnostics. Failures here are
	// non-fatal — the rest of the uninstall must proceed regardless.
	if cr, cerr := claude.Uninstall(claude.Options{
		ProjectDir:  cfg.CWD,
		PlatformDir: platformDir,
		Yes:         true,
	}); cerr != nil {
		out.Warn(fmt.Sprintf("claude assets: %v (continuing)", cerr))
	} else if cr != nil && (len(cr.SkillsRemoved) > 0 || cr.ClaudeMdAction != "") {
		printClaudeSummary(cfg.CWD, cr)
	}

	// Remove CLI wrappers and binaries from user bin dir.
	if binDir, err := platform.UserBinDir(); err == nil {
		for _, name := range []string{"kb", "kb.cmd", "kb-dev", "kb-dev.exe"} {
			p := filepath.Join(binDir, name)
			if err := os.Remove(p); err == nil {
				out.OK(fmt.Sprintf("Removed %s", p))
			}
		}
	}

	// Remove only the pointer generated by kb-create. The project .kb tree can
	// contain user workflows, plugins, and overrides; deleting the whole tree
	// would destroy user work during an otherwise confirmed platform uninstall.
	projectKB := filepath.Join(cfg.CWD, ".kb")
	projectPointer := filepath.Join(projectKB, "kb.config.jsonc")
	if removeGeneratedProjectPointer(projectPointer, platformDir) {
		if err := os.Remove(projectPointer); err == nil {
			out.OK(fmt.Sprintf("Removed generated project pointer %s", projectPointer))
		} else if !os.IsNotExist(err) {
			out.Warn(fmt.Sprintf("Could not remove generated project pointer %s: %v", projectPointer, err))
		}
	}

	// Remove platform directory. On macOS, deeply nested pnpm symlinks can
	// trigger a spurious ENOTEMPTY from the kernel even though RemoveAll is
	// walking the tree correctly. Retry a few times before giving up.
	var removeErr error
	for attempt := range 3 {
		removeErr = os.RemoveAll(platformDir)
		if removeErr == nil {
			break
		}
		time.Sleep(time.Duration(attempt+1) * 200 * time.Millisecond)
	}
	if removeErr != nil {
		return fmt.Errorf("remove platform dir: %w", removeErr)
	}
	out.OK(fmt.Sprintf("Removed %s", platformDir))

	// Clear the "last known install" pointer so subsequent kb-create
	// commands don't auto-discover a platform that no longer exists.
	if err := userstate.Clear(); err != nil {
		out.Warn(fmt.Sprintf("clear user state: %v", err))
	}

	fmt.Println()
	out.OK("Uninstall complete")
	return nil
}

// resolvePlatformDirForUninstall resolves the target platform directory for a
// destructive uninstall. Unlike resolvePlatformDir (used by status/doctor/etc.,
// where falling back to the global "last known platform" in userstate is a
// convenience), uninstall must never guess: userstate is process-wide and
// directory-independent, so running `kb-create uninstall` from a project whose
// own .kb/kb.config.jsonc can't be read (missing, stale, or simply a directory
// kb-create never touched) would otherwise silently target whatever platform
// install happened to run last — reported as deleting a completely different
// project's platform than the one the CLI's own status line implied.
func resolvePlatformDirForUninstall(cmd *cobra.Command) (string, error) {
	if p, _ := cmd.Flags().GetString("platform"); p != "" {
		return p, nil
	}
	if p, _ := cmd.Root().PersistentFlags().GetString("platform"); p != "" {
		return p, nil
	}
	cwd, _ := os.Getwd()
	if cfg, err := config.Read(cwd); err == nil {
		return cfg.Platform, nil
	}
	return "", fmt.Errorf(
		"could not determine the platform to uninstall from the current directory (%s) — "+
			"run this from the project directory, or pass --platform <dir> explicitly", cwd,
	)
}

func removeGeneratedProjectPointer(path, platformDir string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	// WriteProjectConfig skips existing project configs. Only remove the
	// recognizable pointer it created, never a user-authored project config.
	return strings.Contains(string(data), "Set by kb-create — do not remove.") &&
		strings.Contains(string(data), `"dir": `+strconv.Quote(platformDir))
}
