/**
 * @module @kb-labs/core-platform/adapters/notifier
 * Notifier adapter interface for platform-level notification delivery.
 *
 * Topic convention: all notifications are published to 'notification.emitted'.
 * Severity is carried in the payload, not the topic name — cache-backed EventBus
 * implementations poll per literal key and do not support wildcards.
 *
 * Delivery feedback is published to 'notifier-delivery.success' / 'notifier-delivery.failed'
 * (separate namespace — prevents loop if router subscribes to notification.*).
 */

/** Importance level of a notification. */
export type NotificationSeverity = 'info' | 'warn' | 'critical';

/**
 * Intended audience for the notification.
 * - 'all'          — show in Studio UI + dispatch to external channels
 * - 'ui-only'      — Studio only, skip external channels
 * - 'plugins-only' — external channels only, Studio UI suppresses it
 */
export type NotificationAudience = 'all' | 'ui-only' | 'plugins-only';

/** Capabilities a notifier channel may support. */
export type NotificationCapability =
  | 'realtime'     // sub-second delivery (push-based or low-poll)
  | 'rich'         // markdown / HTML formatting
  | 'attachments'  // file / image attachments
  | 'persistent'   // stored on recipient side (email, issue tracker)
  | 'interactive'; // inline buttons / reply actions

/** Payload published to 'notification.emitted'. */
export interface NotificationEvent {
  /** ULID — generated by useNotifications().emit(), stable across retries. */
  id: string;
  title: string;
  body: string;
  /** Default: 'info'. */
  severity?: NotificationSeverity;
  /** Default: 'all'. */
  audience?: NotificationAudience;
  /** Stable event type code, e.g. 'workflow.failed'. Useful for dedup and routing. */
  code?: string;
  /** Optional call-to-action link rendered by rich channels and Studio. */
  action?: { url: string; label: string };
  /** Related platform entity — used for grouping in Studio. */
  entityRef?: { kind: string; id: string };
  /** Originating plugin ID — auto-filled by useNotifications(). */
  source?: string;
  metadata?: Record<string, unknown>;
  /** Unix ms timestamp — auto-filled by useNotifications(). */
  emittedAt: number;
}

/** Filter passed to useNotifications().subscribe(). */
export interface NotificationFilter {
  severity?: NotificationSeverity[];
  /** Match by originating plugin ID. */
  source?: string;
  /** Arbitrary predicate applied after severity/source checks. */
  predicate?: (e: NotificationEvent) => boolean;
}

/**
 * A single delivery channel (Telegram, Slack, Email, …).
 * Implemented by adapter packages; managed and invoked by NotifierRouter.
 * NOT added to IPlatformAdapters — the router owns channel instances.
 */
export interface INotifierChannel {
  /** Stable channel ID matching the config key (e.g. 'telegram-ops'). */
  id: string;
  capabilities: NotificationCapability[];
  /**
   * Optional rate limit hint in requests per second.
   * Used by the router to configure ResourceBroker registration.
   * If absent, the router falls back to a conservative default.
   */
  rateLimit?: number;
  send(event: NotificationEvent): Promise<void>;
  isAvailable(): boolean;
}

/** Published to 'notifier-delivery.success' / 'notifier-delivery.failed'. */
export interface NotifierDeliveryEvent {
  notificationId: string;
  channelId: string;
  success: boolean;
  error?: { message: string; code?: string };
  /** Delivery attempt number (broker may have retried before reaching this). */
  attempt: number;
  at: number;
}

/**
 * Platform-level notifier interface — what platform.notifier exposes to plugins.
 * Implemented by @kb-labs/notifier-router. Registered via adapters.notifier config key.
 *
 * Analogous to ILLMRouter for LLM: wraps eventBus publish/subscribe with
 * autofilling of id/source/emittedAt and filter-based subscription.
 */
export interface INotifier {
  /**
   * Publish a notification event to the platform bus.
   * id, emittedAt, source are auto-filled by the implementation.
   */
  notify(event: Omit<NotificationEvent, 'id' | 'emittedAt'> & { source?: string }): Promise<void>;

  /**
   * Subscribe to notification events. Returns an unsubscribe function.
   * The subscription is NOT automatically cleaned up — callers must call dispose()
   * or use useNotifications(ctx).subscribe() which registers ctx.api.lifecycle.onCleanup.
   */
  subscribe(
    filter: NotificationFilter,
    handler: (event: NotificationEvent) => Promise<void>
  ): () => void;
}
