// Regression coverage for ClickUp 869e6guv5 ("QA: new-user install journey —
// kb-dev start / workflow / doc mismatches broken on fresh install"). The
// original QA pass found these by hand; nothing in the existing e2e or unit
// suite would have caught them, because they're about generated *content*
// (doc comments, help text, error-classification) rather than exit codes.
// These tests run a real `kb-create --yes` install (network required, same
// convention as e2e_test.go) and assert on what actually landed on disk.
package e2e

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestGeneratedWorkflowsUseWorkflowIdFlag pins the fix for the starter
// workflow templates telling users to run `kb workflow run <id>` — which
// `workflow:run` rejects (it requires --workflow-id, no positional arg; see
// plugins/workflow/entry/src/commands/workflow-run.ts). Both files must be
// present (workflow service is on by default) and both "Run:" comments must
// use the real syntax.
func TestGeneratedWorkflowsUseWorkflowIdFlag(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping network test in -short mode")
	}

	bin := binary(t)
	platformDir := t.TempDir()
	projectDir := t.TempDir()
	mustGit(t, projectDir, "init")
	mustGit(t, projectDir, "commit", "--allow-empty", "-m", "init")
	t.Cleanup(func() { _ = os.RemoveAll(filepath.Join(platformDir, "node_modules")) })

	if out, code := run(t, bin, projectDir, "--yes", "--platform", platformDir); code != 0 {
		t.Fatalf("install exited %d:\n%s", code, out)
	}

	for _, name := range []string{"healthcheck.yaml", "deploy-with-approval.yaml"} {
		path := filepath.Join(projectDir, ".kb", "workflows", name)
		data, err := os.ReadFile(path) // #nosec G304 -- path built from t.TempDir()
		if err != nil {
			t.Fatalf("%s not generated: %v", name, err)
		}
		for _, line := range strings.Split(string(data), "\n") {
			if strings.Contains(line, "kb workflow run") && !strings.Contains(line, "--workflow-id") {
				t.Errorf("%s: %q uses `kb workflow run <id>` without --workflow-id, which the CLI rejects", name, strings.TrimSpace(line))
			}
		}
	}
}

// TestGeneratedDemoWorkflowUsesRealCommands pins the fix for --demo's
// demo.yaml, whose comments referenced `kb run demo` and `kb workflow edit
// demo` — neither is a registered command (the real group is `kb workflow
// run --workflow-id <id>`; there is no edit command at all).
func TestGeneratedDemoWorkflowUsesRealCommands(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping network test in -short mode")
	}

	bin := binary(t)
	platformDir := t.TempDir()
	projectDir := t.TempDir()
	mustGit(t, projectDir, "init")
	mustGit(t, projectDir, "commit", "--allow-empty", "-m", "init")
	t.Cleanup(func() { _ = os.RemoveAll(filepath.Join(platformDir, "node_modules")) })

	if out, code := run(t, bin, projectDir, "--yes", "--demo", "--platform", platformDir); code != 0 {
		t.Fatalf("install exited %d:\n%s", code, out)
	}

	path := filepath.Join(projectDir, ".kb", "workflows", "demo.yaml")
	data, err := os.ReadFile(path) // #nosec G304
	if err != nil {
		t.Fatalf("demo.yaml not generated by --demo: %v", err)
	}
	content := string(data)
	if strings.Contains(content, "kb workflow edit") {
		t.Errorf("demo.yaml references `kb workflow edit`, which is not a registered command:\n%s", content)
	}
	if strings.Contains(content, "kb run ") {
		t.Errorf("demo.yaml references `kb run <id>`, which is not a registered command group:\n%s", content)
	}
	for _, line := range strings.Split(content, "\n") {
		if strings.Contains(line, "kb workflow run") && !strings.Contains(line, "--workflow-id") {
			t.Errorf("demo.yaml: %q uses `kb workflow run <id>` without --workflow-id", strings.TrimSpace(line))
		}
	}
}

// TestDemoFlagDoesNotChangeInstalledPackages pins the fix for --demo's help
// text, which claimed "install demo plugins" — DemoMode was never consulted
// when building the services/plugins/binaries selection (only for the
// telemetry consent value), so --demo installed exactly the same packages
// as plain --yes. Compares the two platforms' marketplace.lock installed
// package sets.
func TestDemoFlagDoesNotChangeInstalledPackages(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping network test in -short mode")
	}

	bin := binary(t)

	plainPlatform := t.TempDir()
	plainProject := t.TempDir()
	mustGit(t, plainProject, "init")
	mustGit(t, plainProject, "commit", "--allow-empty", "-m", "init")
	t.Cleanup(func() { _ = os.RemoveAll(filepath.Join(plainPlatform, "node_modules")) })

	demoPlatform := t.TempDir()
	demoProject := t.TempDir()
	mustGit(t, demoProject, "init")
	mustGit(t, demoProject, "commit", "--allow-empty", "-m", "init")
	t.Cleanup(func() { _ = os.RemoveAll(filepath.Join(demoPlatform, "node_modules")) })

	if out, code := run(t, bin, plainProject, "--yes", "--platform", plainPlatform); code != 0 {
		t.Fatalf("plain --yes install exited %d:\n%s", code, out)
	}
	if out, code := run(t, bin, demoProject, "--yes", "--demo", "--platform", demoPlatform); code != 0 {
		t.Fatalf("--yes --demo install exited %d:\n%s", code, out)
	}

	plainPkgs := installedPackageNames(t, plainPlatform)
	demoPkgs := installedPackageNames(t, demoPlatform)

	if plainPkgs != demoPkgs {
		t.Errorf("--demo installed a different package set than plain --yes.\nplain: %s\ndemo:  %s", plainPkgs, demoPkgs)
	}
}

// installedPackageNames returns the sorted, comma-joined set of package
// names present in node_modules/@kb-labs at platformDir — a proxy for "what
// did the installer actually decide to install", independent of version
// pinning noise in marketplace.lock.
func installedPackageNames(t *testing.T, platformDir string) string {
	t.Helper()
	dir := filepath.Join(platformDir, "node_modules", "@kb-labs")
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read %s: %v", dir, err)
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		names = append(names, e.Name())
	}
	return strings.Join(names, ",")
}

// TestDoctorDockerCheckIsAdvisoryNotFatal pins the fix for `kb-create
// doctor` hard-failing the whole run when Docker is missing, even though
// Docker is only needed for devservices.yaml entries with type: docker —
// never for the default Node-based services.
//
// Docker is genuinely installed on most dev/CI machines (it is here), so
// asserting against the ambient environment would never exercise the
// failure branch. Instead this strips PATH down to nothing so node, git,
// and docker are all "not found" — then asserts docker's line is rendered
// as advisory ([WARN]), while node/git (still required) are hard failures
// ([ERR ]). That distinction is exactly what regressed.
func TestDoctorDockerCheckIsAdvisoryNotFatal(t *testing.T) {
	bin := binary(t)

	cmd := exec.CommandContext(context.Background(), bin, "doctor") // #nosec G204 -- fixed binary path + flag
	cmd.Env = []string{"PATH=" + t.TempDir(), "HOME=" + os.Getenv("HOME")}
	outBytes, _ := cmd.CombinedOutput()
	out := string(outBytes)

	sawDockerFailing := false
	for _, line := range strings.Split(out, "\n") {
		lower := strings.ToLower(line)
		if !strings.Contains(lower, "docker") {
			continue
		}
		if strings.Contains(line, "[ERR ]") {
			t.Errorf("docker check line rendered as a hard failure ([ERR ]) with PATH empty, want advisory [WARN]:\n%s", line)
		}
		if strings.Contains(line, "[WARN]") {
			sawDockerFailing = true
		}
	}
	if !sawDockerFailing {
		t.Fatalf("expected the docker check to fail (advisory) with PATH stripped, got no [WARN] docker line:\n%s", out)
	}

	sawNodeHardFail := false
	for _, line := range strings.Split(out, "\n") {
		lower := strings.ToLower(line)
		if strings.Contains(lower, "node") && strings.Contains(line, "[ERR ]") {
			sawNodeHardFail = true
		}
	}
	if !sawNodeHardFail {
		t.Errorf("expected the node check to hard-fail ([ERR ]) with PATH stripped, got none:\n%s", out)
	}
}
