#!/usr/bin/env bash
# Step: Post full pipeline timeline to PR — the complete work history
set -e

cd "${KB_WORKSPACE_ROOT:-$(pwd)}"

# Review status
if [ "$REVIEW_PASSED" = "true" ]; then
  REVIEW_LINE="✅ **Code Review** — passed (0 issues)"
else
  REVIEW_LINE="✅ **Code Review** — ${REVIEW_ISSUES_COUNT} issue(s) found → agent fixed → re-run passed"
fi

# Architect status
if [ "$ARCHITECT_VERDICT" = "APPROVED" ] || [ -z "$ARCHITECT_VERDICT" ]; then
  ARCHITECT_LINE="✅ **Architect Review** — approved"
else
  ARCHITECT_LINE="✅ **Architect Review** — ${ARCHITECT_BLOCKERS_COUNT} blocker(s) found → agent fixed → re-run approved"
fi

# QA status
if [ "$QA_VERDICT" = "PASSED" ] || [ -z "$QA_VERDICT" ]; then
  QA_LINE="✅ **Adversarial QA** — passed (0 bugs)"
else
  QA_LINE="✅ **Adversarial QA** — ${QA_BUGS_COUNT} bug(s) found → agent fixed → re-run passed"
fi

# Functional verification
if [ "$VERIFY_VERDICT" = "PASSED" ]; then
  VERIFY_PHASE="✅"
  VERIFY_LINE="✅ **Functional Verification** — ${VERIFY_CRITERIA_PASSED}/${VERIFY_CRITERIA_TOTAL} acceptance criteria passed"
else
  VERIFY_PHASE="❌ Failed (${VERIFY_CRITERIA_PASSED:-?}/${VERIFY_CRITERIA_TOTAL:-?} criteria)"
  VERIFY_LINE="❌ **Functional Verification** — ${VERIFY_CRITERIA_PASSED:-?}/${VERIFY_CRITERIA_TOTAL:-?} acceptance criteria passed"
fi

BODY="## 📋 Pipeline Timeline — Issue #${ISSUE_NUMBER}

**${ISSUE_TITLE}**

### Phases completed

| # | Phase | Result |
|---|-------|--------|
| 1 | Planning & Approval | ✅ Plan approved |
| 2 | Implementation | ✅ Implemented + self-verified |
| 3 | Code Review | ✅ |
| 4 | Architect Review | ✅ |
| 5 | Adversarial QA | ✅ |
| 6 | Functional Verification | ${VERIFY_PHASE} |
| 7 | Static Gates (type-check + tests) | ✅ |
| 8 | CI | ✅ Green |

### Audit history

${REVIEW_LINE}
${ARCHITECT_LINE}
${QA_LINE}
${VERIFY_LINE}

### Artifacts
See individual PR comments above for full reports from each phase.

---
*Generated by task-to-pr autonomous pipeline*"

gh pr comment "$PR_NUMBER" --repo "$OWNER/$REPO" --body "$BODY" 2>/dev/null || true
