#!/usr/bin/env bash
# Step: Post Architect Review to PR
# Env: ISSUE_NUMBER, OWNER, REPO, PR_NUMBER, ARCHITECT_VERDICT
set -e

REPO_FULL="$OWNER/$REPO"
REVIEW=$(cat "/tmp/kb-architect-review-${ISSUE_NUMBER}.md" 2>/dev/null || echo "Review not available")

ICON="✅"
[ "$ARCHITECT_VERDICT" = "NEEDS_FIXES" ] && ICON="⚠️"

TMP=$(mktemp)
printf '## %s Architect Review\n\n%s\n\n---\n*Generated by KB Labs Architect Agent*' "$ICON" "$REVIEW" > "$TMP"
gh pr comment "$PR_NUMBER" --repo "$REPO_FULL" --body-file "$TMP" 2>/dev/null || true
rm -f "$TMP"
