#!/usr/bin/env bash
# Step: Post Adversarial QA Report to PR
# Env: ISSUE_NUMBER, OWNER, REPO, PR_NUMBER, QA_VERDICT
set -e
# shellcheck source=lib-sanitize.sh
source "$(dirname "$0")/lib-sanitize.sh"

REPO_FULL="$OWNER/$REPO"
REPORT="${QA_REPORT:-$(cat "/tmp/kb-qa-report-${ISSUE_NUMBER}.md" 2>/dev/null)}"
[ -z "$REPORT" ] && REPORT="Report not available"

ICON="✅"
[ "$QA_VERDICT" = "BUGS_FOUND" ] && ICON="🐛"

TMP=$(mktemp)
printf '## %s Adversarial QA Report\n\n**Verdict:** %s\n\n%s\n\n---\n*Generated by KB Labs Adversarial QA Agent*' \
  "$ICON" "$QA_VERDICT" "$REPORT" | sanitize_secrets > "$TMP"
gh pr comment "$PR_NUMBER" --repo "$REPO_FULL" --body-file "$TMP" 2>/dev/null || true
rm -f "$TMP"
