/**
 * Changelog byte freezing (cutover plan §3B, execution plan PR 4 item 7).
 *
 * Release notes are generated by an LLM, which means calling the generator
 * twice for the same candidate can legitimately produce different text. That is
 * fine exactly once. It stops being fine the moment anything binds to those
 * bytes: the mutation plan hashes them, the intent hashes the mutation plan,
 * and an approval covers the intent. Regenerating after that point silently
 * substitutes text nobody approved into a release whose digests still claim the
 * old decision.
 *
 * The fix is not "ask the generator to be deterministic" — it cannot be. It is
 * to make the *second* generation a rejected operation. Once a candidate's
 * changelog is frozen, `freezeChangelog` refuses to overwrite it and hands back
 * the frozen bytes instead.
 *
 * There is no approval gate yet (Workflow is PR 5). PR 4's job is to make
 * regeneration structurally impossible before one exists, so that PR 5 only has
 * to check a digest rather than police a generator.
 */

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  FrozenChangelogSchema,
  ReleaseControlDiagnosticCode,
  canonicalSha256,
  type FrozenChangelog,
} from '@kb-labs/release-manager-contracts';

export function changelogFreezePath(repoRoot: string, candidateId: string): string {
  return join(repoRoot, '.kb', 'release', 'changelog-freeze', `${candidateId}.json`);
}

export class ChangelogFreezeError extends Error {
  readonly code: ReleaseControlDiagnosticCode;
  readonly frozen: FrozenChangelog;

  constructor(code: ReleaseControlDiagnosticCode, message: string, frozen: FrozenChangelog) {
    super(message);
    this.name = 'ChangelogFreezeError';
    this.code = code;
    this.frozen = frozen;
  }
}

function sha256(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

export interface FreezeChangelogInput {
  repoRoot: string;
  flow: string;
  candidateId: string;
  /** Worktree-relative POSIX path → exact file contents. */
  entries: Record<string, string>;
  frozenAt?: string;
}

export interface FreezeChangelogResult {
  frozen: FrozenChangelog;
  path: string;
  /** False when a freeze already existed and the supplied bytes were discarded. */
  created: boolean;
}

/**
 * Freezes changelog bytes for a candidate, or returns the existing freeze.
 *
 * `reuse` semantics matter: an idempotent retry of the same pipeline step must
 * succeed, so a caller that re-freezes *identical* bytes gets `created: false`
 * rather than an error. Only genuinely different bytes are a rejection, because
 * only those represent a substituted decision.
 */
export function freezeChangelog(input: FreezeChangelogInput): FreezeChangelogResult {
  const path = changelogFreezePath(input.repoRoot, input.candidateId);
  const proposed = buildFrozen(input);

  if (existsSync(path)) {
    const existing = FrozenChangelogSchema.parse(JSON.parse(readFileSync(path, 'utf8')));
    if (existing.changelogSha256 === proposed.changelogSha256) {
      return { frozen: existing, path, created: false };
    }
    throw new ChangelogFreezeError(
      ReleaseControlDiagnosticCode.ChangelogAlreadyFrozen,
      `Changelog bytes for candidate ${input.candidateId} were already frozen as ` +
      `${existing.changelogSha256} and cannot be regenerated (proposed ${proposed.changelogSha256}). ` +
      'Cancel the candidate and plan a new one if the notes must change.',
      existing,
    );
  }

  mkdirSync(join(path, '..'), { recursive: true });
  writeFileSync(path, `${JSON.stringify(proposed, null, 2)}\n`);
  return { frozen: proposed, path, created: true };
}

function buildFrozen(input: FreezeChangelogInput): FrozenChangelog {
  const paths = Object.keys(input.entries).sort();
  if (paths.length === 0) {
    throw new Error('freezeChangelog: at least one changelog entry is required');
  }
  const entries = paths.map(path => ({
    path,
    sha256: sha256(input.entries[path]!),
    bytes: Buffer.byteLength(input.entries[path]!, 'utf8'),
    content: input.entries[path]!,
  }));

  return FrozenChangelogSchema.parse({
    schema: 'kb.release-changelog-freeze/1',
    candidateId: input.candidateId,
    flow: input.flow,
    frozenAt: input.frozenAt ?? new Date().toISOString().replace(/\.\d{3}Z$/, 'Z'),
    // Digest over path+bytes only. `frozenAt` is excluded on purpose: a retry
    // that produces identical text a minute later must be recognised as the
    // same decision, and a timestamp would make every retry look like a change.
    changelogSha256: canonicalSha256(entries.map(entry => ({ path: entry.path, sha256: entry.sha256 }))),
    entries,
    signature: null,
  });
}

export function readFrozenChangelog(repoRoot: string, candidateId: string): FrozenChangelog | null {
  const path = changelogFreezePath(repoRoot, candidateId);
  if (!existsSync(path)) { return null; }
  return FrozenChangelogSchema.parse(JSON.parse(readFileSync(path, 'utf8')));
}

/** The `{path: content}` map `release stage` consumes, rebuilt from a freeze. */
export function frozenChangelogEntries(frozen: FrozenChangelog): Record<string, string> {
  return Object.fromEntries(frozen.entries.map(entry => [entry.path, entry.content]));
}
