import { describe, it, expect } from 'vitest';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

import { findWorkspaceRoot, resolveWorkspaceRoot } from '../workspace-root.js';

describe('workspace-root', () => {
  it('resolveWorkspaceRoot() finds the monorepo with a devservices file', () => {
    const root = resolveWorkspaceRoot();
    // Accept either the runtime file (devservices.yaml, generated by kb-create) or
    // the committed dev file (devservices.dev.yaml, always present in git checkouts).
    const hasDevservices =
      existsSync(join(root, '.kb/devservices.yaml')) ||
      existsSync(join(root, '.kb/devservices.dev.yaml'));
    expect(hasDevservices).toBe(true);
  });

  it('findWorkspaceRoot() returns null for an unrelated dir', () => {
    // /tmp is essentially guaranteed to have no .kb/devservices.yaml up the chain.
    const result = findWorkspaceRoot('/tmp');
    // If someone has seeded /tmp with a workspace, we accept null OR a string —
    // but it must never throw.
    expect(result === null || typeof result === 'string').toBe(true);
  });
});
